site_name: meshcaline.org
site_url: https://blog.meshcaline.org
site_dir: public

theme:
    name: mkdocs
    nav_style: light #primary|dark|light
    navigation_depth : 3
    highlightjs: true
#    hljs_style: Arta
    hljs_languages:
        - json
    custom_dir: 'theme_override/'  
    shortcuts:
        help: 72     # h
        next: 78     # n
        previous: 80 # p
        search: 83   # s
        
extra_css:
    - extra.css
    
markdown_extensions:
    - md_in_html
    - attr_list
    
nav:
  - 'meshcaline?': meshcaline.md
  - 'Content':
    - 'REST in Peace': rest-in-peace.md
    - 'Basic meshcaline': basics.md
    - 'Why Hypertext API': hypertext.md
    - 'API Permalinks': permalinks.md
    - 'Paginateable Collections': pagination.md
    - 'API Evolution & Compatibility': evolution.md
    - 'Consumer Driven Response Types': filters.md
  - 'About': about.md  
 
google_analytics: ['UA-52776545-1', 'meshcaline.org']

