site_name: meshcaline.org
site_url: https://blog.meshcaline.org
site_dir: public

theme:
    name: mkdocs
    nav_style: light #primary|dark|light
    navigation_depth : 3
    highlightjs: true
#    hljs_style: Arta
    hljs_languages:
        - json
    custom_dir: 'theme_override/'  

extra_css:
    - extra.css
    
markdown_extensions:
    - md_in_html
    - attr_list
    
nav:
  - 'meshcaline?': meshcaline.md
  - 'Content':
    - 'REST in Peace': rest-in-peace.md
    - 'Basic meshcaline': basics.md
    - 'Why Hypertext API': hypertext.md
    - 'API Permalinks': permalinks.md
    - 'Paginateable Collections': pagination.md
    - 'API Evolution & Compatibility': evolution.md
  - 'About': about.md  
 
copyright: Copyright &copy; <a href="/legal/" rel="copyright"><span itemprop="copyrightHolder">meshcaline.org</span>, <span itemprop="copyrightYear">2014-<script>document.write(new Date().getFullYear())</script></span></a> | <span rel="license"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a></span> | <a href="/privacy/">Privacy Policy</a>
